### ISSUE TITLE
Use env within nuxt.config.js

### ISSUE THREAD

**Issue by vjanoch** [samtgarson/nuxt-env#20]
Is it possible to access the ENV vars within the nuxt.config.js?

Doing it this way the `process.env.*`variables get replaced during the build.
```
    [ 'nuxt-env', {
      keys: [
        { key: 'DOMAIN_DE' },
        { key: 'DOMAIN_AT' },
        { key: 'NUXT_I18N_DIFFERENT_DOMAINS' },
        { key: 'NUXT_I18N_FORWARDED_HOST' }
      ]
    } ],
    [ 'nuxt-i18n', {
      differentDomains: process.env.NUXT_I18N_DIFFERENT_DOMAINS || false,
      forwardedHost: process.env.NUXT_I18N_FORWARDED_HOST || false,
      locales: [
        {
          code: 'de_DE',
          iso: 'de-DE',
          name: 'DE',
          domain: process.env.DOMAIN_DE
        },
        {
          code: 'de_AT',
          iso: 'de-AT',
          name: 'AT',
          domain: process.env.DOMAIN_AT
        }
      ],
      vueI18n: {
        fallbackLocale: 'de_DE'
      },

      strategy: 'prefix'
    } ],
```

Any idea how I could get this to work?

**Comment by vjanoch** [comment]
I've found a very easy solution :-).
During the build I set the values of the ENV vars to the name of the future ENV var.

`.env` used for build:
```
DOMAIN_DE=process.env.DOMAIN_DE
DOMAIN_AT=process.env.DOMAIN_AT
NUXT_I18N_DIFFERENT_DOMAINS=process.env.NUXT_I18N_DIFFERENT_DOMAINS
NUXT_I18N_FORWARDED_HOST=process.env.NUXT_I18N_FORWARDED_HOST
```

`.env` used for start:
```
DOMAIN_DE=local.de:3000
DOMAIN_AT=local.at:3000
NUXT_I18N_DIFFERENT_DOMAINS=true
NUXT_I18N_FORWARDED_HOST=false
```

@samtgarson I think it's worth it to be mentioned in the documentation. Do you want me to create a PR?

**Comment by samtgarson** [comment]
Are you running your app in universal mode?

If so, you should use [`dotenv`](https://www.npmjs.com/package/dotenv) on the first line of your nuxt config to load in your `.env` file.

**Comment by mikl** [comment]
I'm also looking for a way to do this. `dotenv` can't do it, since my environment vars are not from a `.env` file, but rather defined in Kubernetes.

**Comment by aaalekseev** [comment]
Guys, did you solve this issue somehow?

**Comment by xinu** [comment]
> Are you running your app in universal mode?
> 
> If so, you should use [`dotenv`](https://www.npmjs.com/package/dotenv) on the first line of your nuxt config to load in your `.env` file.

dotenv is loading .env files on runtime? in my tests it seems that it is backing it during build

**Comment by samtgarson** [comment]
@xinu it loads them whenever you run the dotenv line. Using nuxt-env should mean your env vars aren't baked in at build time but it depends on your config and how you're using the module

**Comment by samtgarson** [comment]
@mikl @aaalekseev if you're using kubernetes and you have env vars injected into your deployment then they should be available on `process.env`

**Comment by syffs** [comment]
> @mikl @aaalekseev if you're using kubernetes and you have env vars injected into your deployment then they should be available on `process.env`

@samtgarson accessing env vars at runtime from process.env is one thing, but how do you make sure they're actually resolved at runtime instead of build time within `nuxt.config.js` ?

**Comment by samtgarson** [comment]
@syffs you can use https://github.com/samtgarson/nuxt-env to resolve env vars at runtime instead of build time.

**Comment by samtgarson** [comment]
@syffs I'm not sure I follow, if use this library with your app in Universal mode your env vars shouldn't get resolved at build time (although whatever is in your `process.env` at build time will be used, and the same for runtime)

Could you provide a little more information about your setup?

I'm still not quite clear on what this issue is reporting. Could anyone provide a simple reproduction?

**Comment by alessandrocaprarelli** [comment]
Having the same issue here.

We set some env vars in nuxt-env inside nuxt.config.js and we would like to use those vars inside nuxt.config.js. Something like the following:
```
router: {
  base: this.$env.NUXT_BASE_DIR // this var should be resolved at runtime and not build time
}
```

**Comment by samtgarson** [comment]
@alessandrocaprarelli that wouldn't be possible, as the `nuxt.config.js` file is a plain js file that is run before Nuxt is even instantiated, but you can just set the router base to be `process.env.NUXT_BASE_DIR`, no?

**Comment by samtgarson** [comment]
The original issue is actually an issue with `nuxt-i18n`, not `nuxt-env`. If you're having issues with other libraries baking their configuration in at build time, you need to raise an issue with those libraries, therefore I'm closing this issue.

@vjanoch @mikl @aaalekseev @syffs we use this library in kubernetes in production without any issues. If you're having issues with baked environment variables, please ensure the issue is with nuxt-env and not with a different third party library—if it is, feel free to open another issue.

**Comment by alessandrocaprarelli** [comment]
@samtgarson The problem is that the environment variable is picked up at build time (run in our CI system) and not at runtime.

**Comment by samtgarson** [comment]
@alessandrocaprarelli If you're referring to the router base, then that's Nuxt behaviour and there's nothing this library can do about that. I'd suggest looking at a module to modify the router options at runtime, or raise an issue with Nuxt directly.
